[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --minify --themesDir ../.. --baseURL https://health-sci-j-demo.netlify.app"

[context.production.environment]
HUGO_VERSION = "0.74.2"
HUGO_ENV = "production"